In [1]:
# OPTIONAL: Load the "autoreload" extension so that code can change
%reload_ext autoreload

# OPTIONAL: always reload modules so that as you change code in src, it gets loaded
%autoreload 2

import sys
sys.path.append('../src')

from datetime import datetime
import os
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view as sww
import pandas as pd
import re

from metadata import metadata
from utils import list_subdir_filter as lsd, unique

global md
md = metadata()

global markers
markers = list(md.markers)

In [2]:
def get_id(f):
    if re.search('A40(\.|_)', f):
        return re.sub('^.*A40.([0-9]{4}).*$', '\\1', f)
    else:
        return re.sub('^.*segmentation_([0-9]+).*$', '\\1', f)

def date_of_files(files):
    try:
        return max([os.path.getctime(f) for f in files if os.path.exists(f)])
    except:
        return 0


all_samples = lsd(os.path.join(md.folders['images'], 'mouse'))
all_imgs = lsd(os.path.join(md.folders['images'], 'mouse'), True, '\.tif')
all_segs = lsd(md.folders['segmented'], True)
pickle_files = lsd(md.folders['regionprops'], False, 'A40_')


all_samples_ids, all_imgs_ids, all_segs_ids, all_pickles = list(map(
    lambda x: unique([get_id(f) for f in x]), 
    [all_samples, all_imgs, all_segs, pickle_files]
))

In [10]:
all_imgs_ids

[]

In [3]:
xfile = pd.read_excel(lsd(md.folders['images'], True, 'xls')[0])
xfile['id_code'] = [re.sub('A40\.', '', l) for l in xfile.Identification]
#xfile = xfile.loc[xfile['id_code'].isin(slide_ids)].sort_values('id_code')

In [4]:
xfile['sam'] = xfile['id_code'].isin(all_samples_ids)
xfile['img'] = xfile['id_code'].isin(all_imgs_ids)
xfile['seg'] = xfile['id_code'].isin(all_segs_ids)
xfile['regions'] = xfile['id_code'].isin(all_pickles)

In [5]:
xfile.loc[xfile.sam & -xfile.img]

,Code,Identification,Group,Condition,File,id_code,sam,img,seg,regions
1,JNUDE_04,A40.2311,wt_ctr_2,wt_ctr,non,2311,True,False,True,False
2,JNUDE_05,A40.2303,wt_ctr_4,wt_ctr,20231006_124507_3_NPRUS9_Run 65_A40.2303.csv,2303,True,False,True,False
3,JNUDE_06,A40.2403,wt_osi_3,wt_TT,A40_2403.csv,2403,True,False,True,False
4,JNUDE_07,A40.2337,wt_ctr_6,wt_ctr,20230915_150044_1_h1fE0K_Run 54_A40.2337.csv,2337,True,False,True,False
5,JNUDE_08,A40.2397,wt_osi_7,wt_TT,non,2397,True,False,True,False
6,JNUDE_09,A40.2404,wt_osi_1,wt_TT,20230915_150044_3_nCS5op_Run 54_A40.2404.csv,2404,True,False,True,False
7,JNUDE_10,A40.2405,wt_osi_4,wt_TT,A40_2405.csv,2405,True,False,True,False
8,JNUDE_11,A40.2312,wt_ctr_5,wt_ctr,20230915_150044_2_GulsMx_Run 54_A40.2312.csv,2312,True,False,True,False
9,JNUDE_12,A40.2406,wt_osi_5,wt_TT,non,2406,True,False,True,False
10,JNUDE_13,A40.2426,wt_osi_6,wt_TT,A40_2426.csv,2426,True,False,True,False
11,JNUDE_14,A40.2294,wt_ctr_3,wt_ctr,A40_2294.csv,2294,True,False,True,True
12,JNUDE_16,A40.2419,ko_osi_2,ko_TT,20230914_173737_4_Er644v_Run 53_A40.2419.csv,2419,True,False,True,False
13,JNUDE_17,A40.2429,ko_osi_3,ko_TT,non,2429,True,False,True,False
15,JNUDE_19,A40.2416,ko_ctr_2,ko_ctr,20230914_173736_3_D61Agp_Run 53_A40.2416.csv,2416,True,False,True,False
16,JNUDE_22,A40.2430,ko_osi_6,ko_TT,20230918_152613_3_9pzeAy_Run 55_A40.2430.csv,2430,True,False,True,False
18,JNUDE_23_li,A40.2393,ko_ctr_3,ko_ctr,20230921_134356_1_EgBQRX_Run 59_A40.2393.csv,2393,True,False,True,False
19,JNUDE_24,A40.2300,ko_ctr_1,ko_ctr,20230831_152523_1_ExRj6r_Run52_A40.2300.csv,2300,True,False,True,True
20,JNUDE_25,A40.2432,ko_ctr_4,ko_ctr,20230920_173137_3_371MkO_Run 57_A40.2432.csv,2432,True,False,False,False
21,JNUDE_26,A40.2427,ko_ctr_5,ko_ctr,20230830_123250_4_QIfXt0_Run49_A40.2427.csv,2427,True,False,True,False
22,JNUDE_27,A40.2433,ko_ctr_6,ko_ctr,non,2433,True,False,False,False
23,JNUDE_28,A40.2338,ko_ctr_7,ko_ctr,20230829_102724_2_4kJsI2_Run48_A40.2338.csv,2338,True,False,False,False
24,JNUDE_29,A40.2255,resc_ctr_2,res_ctr,20230914_173736_1_AWcjm5_Run 53_A40.2255.csv,2255,True,False,True,True
25,JNUDE_30,A40.2256,resc_ctr_1,res_ctr,20230918_152613_1_axt1oM_Run 55_A40.2256.csv,2256,True,False,True,True
26,JNUDE_31,A40.2407,resc_osi_1,res_TT,20230915_150044_4_fCLiUg_Run 54_A40.2407.csv,2407,True,False,True,False
27,JNUDE_32,A40.2417,resc_osi_6,res_TT,20230921_134356_2_ScAZxG_Run 59_A40.2417.csv,2417,True,False,True,False
28,JNUDE_33,A40.2304,resc_ctr_4,res_ctr,20230918_152613_4_f8gscq_Run 55_A40.2304.csv,2304,True,False,True,False
29,JNUDE_34,A40.2314,resc_ctr_6,res_ctr,20230830_123250_2_qfUzAH_Run50_A40.2314.csv,2314,True,False,True,False
30,JNUDE_35,A40.2339,resc_ctr_5,res_ctr,20230919_133019_3_8DUUKe_Run 56_A40.2339.csv,2339,True,False,True,False
31,JNUDE_36,A40.2305,resc_ctr_7,res_ctr,20230829_102725_3_QRVIW1_Run48_A40.2305.csv,2305,True,False,False,False
32,JNUDE_38,A40.2408,resc_osi_2,res_TT,20230918_152613_2_dXIRi6_Run 55_A40.2408.csv,2408,True,False,True,False
33,JNUDE_39,A40.2420,resc_osi_7,res_TT,20230921_134356_3_yurmP9_Run 59_A40.2420.csv,2420,True,False,True,False
34,JNUDE_40,A40.2268,resc_ctr_3,res_ctr,20230829_102725_4_zKbvse_Run48_A40.2268.csv,2268,True,False,False,False
36,JNUDE_42,A40.2418,resc_osi_5,res_TT,20230830_123250_3_NhG7zF_Run50_A40.2418.csv,2418,True,False,True,False

In [6]:
seg_dir = os.path.join(md.folders['segmented'], 'cellpose')

xfile['complete_AF_removal'] = [
    sum([
        os.path.exists(os.path.join(md.folders['bg_removed'], f'clean_{marker}_{img_id}.npy')) 
        for marker in markers]
       ) == 9 
    for img_id in xfile.id_code
]

xfile['AF_time'] = [
    datetime.fromtimestamp(date_of_files([
        os.path.join(md.folders['bg_removed'], f'clean_{marker}_{img_id}.npy')
        for marker in markers
    ])).strftime('%Y.%m.%d %H:%M')
    for img_id in xfile.id_code
    ]

xfile['complete_segmentation'] = [(len(lsd(seg_dir, True, f'A40_{i}_[0-9]_dapi1\.npy')) == 10) for i in xfile.id_code]
xfile.sort_values(['Condition', 'id_code'])

,Code,Identification,Group,Condition,File,id_code,sam,img,seg,regions,complete_AF_removal,AF_time,complete_segmentation
12,JNUDE_16,A40.2419,ko_osi_2,ko_TT,20230914_173737_4_Er644v_Run 53_A40.2419.csv,2419,True,False,True,False,False,1970.01.01 01:00,True
14,JNUDE_18,A40.2428,ko_osi_4,ko_TT,20230919_133019_4_UuguYd_Run 56_A40.2428.csv,2428,False,False,False,False,False,1970.01.01 01:00,False
13,JNUDE_17,A40.2429,ko_osi_3,ko_TT,non,2429,True,False,True,False,False,1970.01.01 01:00,True
16,JNUDE_22,A40.2430,ko_osi_6,ko_TT,20230918_152613_3_9pzeAy_Run 55_A40.2430.csv,2430,True,False,True,False,False,1970.01.01 01:00,False
19,JNUDE_24,A40.2300,ko_ctr_1,ko_ctr,20230831_152523_1_ExRj6r_Run52_A40.2300.csv,2300,True,False,True,True,False,1970.01.01 01:00,True
17,JNUDE_23_re,A40.2313,ko_ctr_3,ko_ctr,A40_2313.csv,2313,False,False,False,False,False,1970.01.01 01:00,False
23,JNUDE_28,A40.2338,ko_ctr_7,ko_ctr,20230829_102724_2_4kJsI2_Run48_A40.2338.csv,2338,True,False,False,False,False,1970.01.01 01:00,False
18,JNUDE_23_li,A40.2393,ko_ctr_3,ko_ctr,20230921_134356_1_EgBQRX_Run 59_A40.2393.csv,2393,True,False,True,False,False,1970.01.01 01:00,True
15,JNUDE_19,A40.2416,ko_ctr_2,ko_ctr,20230914_173736_3_D61Agp_Run 53_A40.2416.csv,2416,True,False,True,False,False,1970.01.01 01:00,True
21,JNUDE_26,A40.2427,ko_ctr_5,ko_ctr,20230830_123250_4_QIfXt0_Run49_A40.2427.csv,2427,True,False,True,False,False,1970.01.01 01:00,True
20,JNUDE_25,A40.2432,ko_ctr_4,ko_ctr,20230920_173137_3_371MkO_Run 57_A40.2432.csv,2432,True,False,False,False,False,1970.01.01 01:00,False
22,JNUDE_27,A40.2433,ko_ctr_6,ko_ctr,non,2433,True,False,False,False,False,1970.01.01 01:00,False
41,human_3_pre,LCCH_1271_T0,pre,pat,20230927_100407_3_m3EX2u_Run 64_LCCH-1271-T0.csv,LCCH_1271_T0,False,False,False,False,False,1970.01.01 01:00,False
42,human_3_post,LCCH_1271_T1,post,pat,20230927_100407_4_JMvkUm_Run 64_LCCH-1271-T1.csv,LCCH_1271_T1,False,False,False,False,False,1970.01.01 01:00,False
37,human_1_pre,LCCH_381_T0,pre,pat,20230922_103442_4_zlXGp6_Run 60_LCCH-381-T0.csv,LCCH_381_T0,False,False,False,False,False,1970.01.01 01:00,False
38,human_1_post,LCCH_381_T1,post,pat,20230926_111532_4_SBRcSE_Run 63_LCCH-381-T1.csv,LCCH_381_T1,False,False,False,False,False,1970.01.01 01:00,False
39,human_2_pre,LCCH_907_T0,pre,pat,20230927_100407_1_2pXB4I_Run 64_LCCH-907-T0.csv,LCCH_907_T0,False,False,False,False,False,1970.01.01 01:00,False
40,human_2_post,LCCH_907_T1,post,pat,20230927_100407_2_GlWKa2_Run 64_LCCH-907-T1.csv,LCCH_907_T1,False,False,False,False,False,1970.01.01 01:00,False
26,JNUDE_31,A40.2407,resc_osi_1,res_TT,20230915_150044_4_fCLiUg_Run 54_A40.2407.csv,2407,True,False,True,False,False,1970.01.01 01:00,True
32,JNUDE_38,A40.2408,resc_osi_2,res_TT,20230918_152613_2_dXIRi6_Run 55_A40.2408.csv,2408,True,False,True,False,False,1970.01.01 01:00,True
35,JNUDE_41,A40.2409,resc_osi_3,res_TT,A40_2409_cell.csv,2409,False,False,False,False,False,1970.01.01 01:00,False
27,JNUDE_32,A40.2417,resc_osi_6,res_TT,20230921_134356_2_ScAZxG_Run 59_A40.2417.csv,2417,True,False,True,False,False,1970.01.01 01:00,True
36,JNUDE_42,A40.2418,resc_osi_5,res_TT,20230830_123250_3_NhG7zF_Run50_A40.2418.csv,2418,True,False,True,False,False,1970.01.01 01:00,True
33,JNUDE_39,A40.2420,resc_osi_7,res_TT,20230921_134356_3_yurmP9_Run 59_A40.2420.csv,2420,True,False,True,False,False,1970.01.01 01:00,True
24,JNUDE_29,A40.2255,resc_ctr_2,res_ctr,20230914_173736_1_AWcjm5_Run 53_A40.2255.csv,2255,True,False,True,True,False,1970.01.01 01:00,True
25,JNUDE_30,A40.2256,resc_ctr_1,res_ctr,20230918_152613_1_axt1oM_Run 55_A40.2256.csv,2256,True,False,True,True,False,1970.01.01 01:00,True
34,JNUDE_40,A40.2268,resc_ctr_3,res_ctr,20230829_102725_4_zKbvse_Run48_A40.2268.csv,2268,True,False,False,False,False,1970.01.01 01:00,False
28,JNUDE_33,A40.2304,resc_ctr_4,res_ctr,20230918_152613_4_f8gscq_Run 55_A40.2304.csv,2304,True,False,True,False,False,1970.01.01 01:00,True
31,JNUDE_36,A40.2305,resc_ctr_7,res_ctr,20230829_102725_3_QRVIW1_Run48_A40.2305.csv,2305,True,False,False,False,False,1970.01.01 01:00,False
29,JNUDE_34,A40.2314,resc_ctr_6,res_ctr,20230830_123250_2_qfUzAH_Run50_A40.2314.csv,2314,True,False,True,False,False,1970.01.01 01:00,True
30,JNUDE_35,A40.2339,resc_ctr_5,res_ctr,20230919_133019_3_8DUUKe_Run 56_A40.2339.csv,2339,True,False,True,False,False,1970.01.01 01:00,True
5,JNUDE_08,A40.2397,wt_osi_7,wt_TT,non,2397,True,False,True,False,False,1970.01.01 01:00,True
3,JNUDE_06,A40.2403,wt_osi_3,wt_TT,A40_2403.csv,2403,True,False,True,False,False,1970.01.01 01:00,True
6,JNUDE_09,A40.2404,wt_osi_1,wt_TT,20230915_150044_3_nCS5op_Run 54_A40.2404.csv,2404,True,False,True,False,False,1970.01.01 01:00,True
7,JNUDE_10,A40.2405,wt_osi_4,wt_TT,A40_2405.csv,2405,True,False,True,False,False,1970.01.01 01:00,False
9,JNUDE_12,A40.2406,wt_osi_5,wt_TT,non,2406,True,False,True,False,False,1970.01.01 01:00,True
10,JNUDE_13,A40.2426,wt_osi_6,wt_TT,A40_2426.csv,2426,True,False,True,False,False,1970.01.01 01:00,True
11,JNUDE_14,A40.2294,wt_ctr_3,wt_ctr,A40_2294.csv,2294,True,False,True,True,False,1970.01.01 01:00,True
0,JNUDE_03,A40.2302,wt_ctr_1,wt_ctr,non,2302,False,False,False,False,False,1970.01.01 01:00,False
2,JNUDE_05,A40.2303,wt_ctr_4,wt_ctr,20231006_124507_3_NPRUS9_Run 65_A40.2303.csv,2303,True,False,True,False,False,1970.01.01 01:00,True
1,JNUDE_04,A40.2311,wt_ctr_2,wt_ctr,non,2311,True,False,True,False,False,1970.01.01 01:00,True
8,JNUDE_11,A40.2312,wt_ctr_5,wt_ctr,20230915_150044_2_GulsMx_Run 54_A40.2312.csv,2312,True,False,True,False,False,1970.01.01 01:00,True
4,JNUDE_07,A40.2337,wt_ctr_6,wt_ctr,20230915_150044_1_h1fE0K_Run 54_A40.2337.csv,2337,True,False,True,False,False,1970.01.01 01:00,True

In [7]:
id_condition_table = xfile.loc[xfile.img, ['id_code', 'Condition', 'complete_AF_removal', 'complete_segmentation', 'regions']].sort_values(['Condition', 'id_code'])
id_condition_table.to_csv('../data/interim/id_condition_table.csv')
id_condition_table

Empty DataFrame
Columns: [id_code, Condition, complete_AF_removal, complete_segmentation, regions]
Index: []

In [8]:
# seg_dir = os.path.join(md.folders['segmented'], 'cellpose')

# markers = list(md.markers)
# for img_id in sorted(xfile.id_code.unique()):
#     ss = sum([os.path.exists(os.path.join(md.folders['bg_removed'], f'clean_{marker}_{img_id}.npy')) for marker in markers])
#     ll = len(lsd(seg_dir, False, f'A40_{img_id}_dapi1_[0-9][0-9]\.npy'))

#     print(f'{img_id} - {ss} - {ll}')

# # len(lsd(seg_dir, False, f'A40_{tile_code}_dapi1_[0-9][0-9]\.npy')) != 10:
# #         print(f'{tile_code} is sus. Skipping...')
# #         return None

In [9]:
sum(xfile.img)

32

In [9]:
xfile

,Code,Identification,Group,Condition,File,id_code,sam,img,seg,regions,complete_AF_removal,AF_time,complete_segmentation
0,JNUDE_03,A40.2302,wt_ctr_1,wt_ctr,non,2302,False,False,False,False,False,1970.01.01 01:00,False
1,JNUDE_04,A40.2311,wt_ctr_2,wt_ctr,non,2311,True,False,True,False,False,1970.01.01 01:00,True
2,JNUDE_05,A40.2303,wt_ctr_4,wt_ctr,20231006_124507_3_NPRUS9_Run 65_A40.2303.csv,2303,True,False,True,False,False,1970.01.01 01:00,True
3,JNUDE_06,A40.2403,wt_osi_3,wt_TT,A40_2403.csv,2403,True,False,True,False,False,1970.01.01 01:00,True
4,JNUDE_07,A40.2337,wt_ctr_6,wt_ctr,20230915_150044_1_h1fE0K_Run 54_A40.2337.csv,2337,True,False,True,False,False,1970.01.01 01:00,True
5,JNUDE_08,A40.2397,wt_osi_7,wt_TT,non,2397,True,False,True,False,False,1970.01.01 01:00,True
6,JNUDE_09,A40.2404,wt_osi_1,wt_TT,20230915_150044_3_nCS5op_Run 54_A40.2404.csv,2404,True,False,True,False,False,1970.01.01 01:00,True
7,JNUDE_10,A40.2405,wt_osi_4,wt_TT,A40_2405.csv,2405,True,False,True,False,False,1970.01.01 01:00,False
8,JNUDE_11,A40.2312,wt_ctr_5,wt_ctr,20230915_150044_2_GulsMx_Run 54_A40.2312.csv,2312,True,False,True,False,False,1970.01.01 01:00,True
9,JNUDE_12,A40.2406,wt_osi_5,wt_TT,non,2406,True,False,True,False,False,1970.01.01 01:00,True
10,JNUDE_13,A40.2426,wt_osi_6,wt_TT,A40_2426.csv,2426,True,False,True,False,False,1970.01.01 01:00,True
11,JNUDE_14,A40.2294,wt_ctr_3,wt_ctr,A40_2294.csv,2294,True,False,True,True,False,1970.01.01 01:00,True
12,JNUDE_16,A40.2419,ko_osi_2,ko_TT,20230914_173737_4_Er644v_Run 53_A40.2419.csv,2419,True,False,True,False,False,1970.01.01 01:00,True
13,JNUDE_17,A40.2429,ko_osi_3,ko_TT,non,2429,True,False,True,False,False,1970.01.01 01:00,True
14,JNUDE_18,A40.2428,ko_osi_4,ko_TT,20230919_133019_4_UuguYd_Run 56_A40.2428.csv,2428,False,False,False,False,False,1970.01.01 01:00,False
15,JNUDE_19,A40.2416,ko_ctr_2,ko_ctr,20230914_173736_3_D61Agp_Run 53_A40.2416.csv,2416,True,False,True,False,False,1970.01.01 01:00,True
16,JNUDE_22,A40.2430,ko_osi_6,ko_TT,20230918_152613_3_9pzeAy_Run 55_A40.2430.csv,2430,True,False,True,False,False,1970.01.01 01:00,False
17,JNUDE_23_re,A40.2313,ko_ctr_3,ko_ctr,A40_2313.csv,2313,False,False,False,False,False,1970.01.01 01:00,False
18,JNUDE_23_li,A40.2393,ko_ctr_3,ko_ctr,20230921_134356_1_EgBQRX_Run 59_A40.2393.csv,2393,True,False,True,False,False,1970.01.01 01:00,True
19,JNUDE_24,A40.2300,ko_ctr_1,ko_ctr,20230831_152523_1_ExRj6r_Run52_A40.2300.csv,2300,True,False,True,True,False,1970.01.01 01:00,True
20,JNUDE_25,A40.2432,ko_ctr_4,ko_ctr,20230920_173137_3_371MkO_Run 57_A40.2432.csv,2432,True,False,False,False,False,1970.01.01 01:00,False
21,JNUDE_26,A40.2427,ko_ctr_5,ko_ctr,20230830_123250_4_QIfXt0_Run49_A40.2427.csv,2427,True,False,True,False,False,1970.01.01 01:00,True
22,JNUDE_27,A40.2433,ko_ctr_6,ko_ctr,non,2433,True,False,False,False,False,1970.01.01 01:00,False
23,JNUDE_28,A40.2338,ko_ctr_7,ko_ctr,20230829_102724_2_4kJsI2_Run48_A40.2338.csv,2338,True,False,False,False,False,1970.01.01 01:00,False
24,JNUDE_29,A40.2255,resc_ctr_2,res_ctr,20230914_173736_1_AWcjm5_Run 53_A40.2255.csv,2255,True,False,True,True,False,1970.01.01 01:00,True
25,JNUDE_30,A40.2256,resc_ctr_1,res_ctr,20230918_152613_1_axt1oM_Run 55_A40.2256.csv,2256,True,False,True,True,False,1970.01.01 01:00,True
26,JNUDE_31,A40.2407,resc_osi_1,res_TT,20230915_150044_4_fCLiUg_Run 54_A40.2407.csv,2407,True,False,True,False,False,1970.01.01 01:00,True
27,JNUDE_32,A40.2417,resc_osi_6,res_TT,20230921_134356_2_ScAZxG_Run 59_A40.2417.csv,2417,True,False,True,False,False,1970.01.01 01:00,True
28,JNUDE_33,A40.2304,resc_ctr_4,res_ctr,20230918_152613_4_f8gscq_Run 55_A40.2304.csv,2304,True,False,True,False,False,1970.01.01 01:00,True
29,JNUDE_34,A40.2314,resc_ctr_6,res_ctr,20230830_123250_2_qfUzAH_Run50_A40.2314.csv,2314,True,False,True,False,False,1970.01.01 01:00,True
30,JNUDE_35,A40.2339,resc_ctr_5,res_ctr,20230919_133019_3_8DUUKe_Run 56_A40.2339.csv,2339,True,False,True,False,False,1970.01.01 01:00,True
31,JNUDE_36,A40.2305,resc_ctr_7,res_ctr,20230829_102725_3_QRVIW1_Run48_A40.2305.csv,2305,True,False,False,False,False,1970.01.01 01:00,False
32,JNUDE_38,A40.2408,resc_osi_2,res_TT,20230918_152613_2_dXIRi6_Run 55_A40.2408.csv,2408,True,False,True,False,False,1970.01.01 01:00,True
33,JNUDE_39,A40.2420,resc_osi_7,res_TT,20230921_134356_3_yurmP9_Run 59_A40.2420.csv,2420,True,False,True,False,False,1970.01.01 01:00,True
34,JNUDE_40,A40.2268,resc_ctr_3,res_ctr,20230829_102725_4_zKbvse_Run48_A40.2268.csv,2268,True,False,False,False,False,1970.01.01 01:00,False
35,JNUDE_41,A40.2409,resc_osi_3,res_TT,A40_2409_cell.csv,2409,False,False,False,False,False,1970.01.01 01:00,False
36,JNUDE_42,A40.2418,resc_osi_5,res_TT,20230830_123250_3_NhG7zF_Run50_A40.2418.csv,2418,True,False,True,False,False,1970.01.01 01:00,True
37,human_1_pre,LCCH_381_T0,pre,pat,20230922_103442_4_zlXGp6_Run 60_LCCH-381-T0.csv,LCCH_381_T0,False,False,False,False,False,1970.01.01 01:00,False
38,human_1_post,LCCH_381_T1,post,pat,20230926_111532_4_SBRcSE_Run 63_LCCH-381-T1.csv,LCCH_381_T1,False,False,False,False,False,1970.01.01 01:00,False
39,human_2_pre,LCCH_907_T0,pre,pat,20230927_100407_1_2pXB4I_Run 64_LCCH-907-T0.csv,LCCH_907_T0,False,False,False,False,False,1970.01.01 01:00,False
40,human_2_post,LCCH_907_T1,post,pat,20230927_100407_2_GlWKa2_Run 64_LCCH-907-T1.csv,LCCH_907_T1,False,False,False,False,False,1970.01.01 01:00,False
41,human_3_pre,LCCH_1271_T0,pre,pat,20230927_100407_3_m3EX2u_Run 64_LCCH-1271-T0.csv,LCCH_1271_T0,False,False,False,False,False,1970.01.01 01:00,False
42,human_3_post,LCCH_1271_T1,post,pat,20230927_100407_4_JMvkUm_Run 64_LCCH-1271-T1.csv,LCCH_1271_T1,False,False,False,False,False,1970.01.01 01:00,False